ingestion:
  target: local
  outputs:
    local:
      type: clickhouse
      host: localhost
      port: 30123
      schema: default
      user: default
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      secure: false
      engine: "ReplacingMergeTree(_version)"
      settings:
        allow_nullable_key: 1
    k8s:
      type: clickhouse
      host: insight-clickhouse.insight.svc.cluster.local
      port: 8123
      schema: default
      user: default
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      secure: false
      engine: "ReplacingMergeTree(_version)"
      settings:
        allow_nullable_key: 1
