// Stub for GET /v1/organizations/analytics/summaries
// Returns per-day organization summary records. Each record has a `date` field;
// the HTTP layer filters by the requested starting_date/ending_date range.

module.exports = [
  {
    date: '2026-04-01',
    daily_active_user_count: 3,
    weekly_active_user_count: 3,
    monthly_active_user_count: 3,
    assigned_seat_count: 10,
    pending_invite_count: 1,
    cowork_daily_active_user_count: 1,
    cowork_weekly_active_user_count: 1,
    cowork_monthly_active_user_count: 1,
  },
  {
    date: '2026-04-02',
    daily_active_user_count: 2,
    weekly_active_user_count: 3,
    monthly_active_user_count: 3,
    assigned_seat_count: 10,
    pending_invite_count: 1,
    cowork_daily_active_user_count: 0,
    cowork_weekly_active_user_count: 1,
    cowork_monthly_active_user_count: 1,
  },
  {
    date: '2026-04-03',
    daily_active_user_count: 4,
    weekly_active_user_count: 4,
    monthly_active_user_count: 4,
    assigned_seat_count: 11,
    pending_invite_count: 0,
    cowork_daily_active_user_count: 2,
    cowork_weekly_active_user_count: 2,
    cowork_monthly_active_user_count: 2,
  },
  {
    date: '2026-04-04',
    daily_active_user_count: 5,
    weekly_active_user_count: 5,
    monthly_active_user_count: 5,
    assigned_seat_count: 11,
    pending_invite_count: 0,
    cowork_daily_active_user_count: 2,
    cowork_weekly_active_user_count: 2,
    cowork_monthly_active_user_count: 2,
  },
  {
    date: '2026-04-05',
    daily_active_user_count: 3,
    weekly_active_user_count: 5,
    monthly_active_user_count: 5,
    assigned_seat_count: 11,
    pending_invite_count: 0,
    cowork_daily_active_user_count: 1,
    cowork_weekly_active_user_count: 2,
    cowork_monthly_active_user_count: 2,
  },
];
