// Stub for GET /v1/organizations/analytics/users
// Returns per-user daily engagement records. The API does NOT include a `date`
// field in the response — the date comes from the request parameter. Clients
// (like the Insight connector) attach it via AddFields.

module.exports = [
  {
    user: { id: 'user_alice', email_address: 'alice@example.com' },
    chat_metrics: {
      distinct_conversation_count: 5,
      message_count: 42,
      distinct_projects_created_count: 1,
      distinct_projects_used_count: 2,
      distinct_files_uploaded_count: 3,
      distinct_artifacts_created_count: 1,
      thinking_message_count: 2,
      distinct_skills_used_count: 1,
      connectors_used_count: 0,
    },
    claude_code_metrics: {
      core_metrics: {
        commit_count: 8,
        pull_request_count: 1,
        lines_of_code: { added_count: 245, removed_count: 12 },
        distinct_session_count: 3,
      },
      tool_actions: {
        edit_tool: { accepted_count: 5, rejected_count: 1 },
        multi_edit_tool: { accepted_count: 0, rejected_count: 0 },
        write_tool: { accepted_count: 2, rejected_count: 0 },
        notebook_edit_tool: { accepted_count: 0, rejected_count: 0 },
      },
    },
    web_search_count: 2,
    office_metrics: {
      excel: {
        distinct_session_count: 0,
        message_count: 0,
        skills_used_count: 0,
        distinct_skills_used_count: 0,
        connectors_used_count: 0,
        distinct_connectors_used_count: 0,
      },
      powerpoint: {
        distinct_session_count: 0,
        message_count: 0,
        skills_used_count: 0,
        distinct_skills_used_count: 0,
        connectors_used_count: 0,
        distinct_connectors_used_count: 0,
      },
    },
    cowork_metrics: {
      distinct_session_count: 1,
      message_count: 7,
      action_count: 14,
      dispatch_turn_count: 2,
      skills_used_count: 2,
      distinct_skills_used_count: 1,
      connectors_used_count: 3,
      distinct_connectors_used_count: 2,
    },
  },
  {
    user: { id: 'user_bob', email_address: 'bob@example.com' },
    chat_metrics: {
      distinct_conversation_count: 12,
      message_count: 103,
      distinct_projects_created_count: 0,
      distinct_projects_used_count: 3,
      distinct_files_uploaded_count: 1,
      distinct_artifacts_created_count: 4,
      thinking_message_count: 8,
      distinct_skills_used_count: 3,
      connectors_used_count: 2,
    },
    claude_code_metrics: {
      core_metrics: {
        commit_count: 2,
        pull_request_count: 0,
        lines_of_code: { added_count: 38, removed_count: 4 },
        distinct_session_count: 1,
      },
      tool_actions: {
        edit_tool: { accepted_count: 3, rejected_count: 2 },
        multi_edit_tool: { accepted_count: 1, rejected_count: 0 },
        write_tool: { accepted_count: 0, rejected_count: 0 },
        notebook_edit_tool: { accepted_count: 0, rejected_count: 0 },
      },
    },
    web_search_count: 5,
    office_metrics: {
      excel: {
        distinct_session_count: 2,
        message_count: 14,
        skills_used_count: 3,
        distinct_skills_used_count: 2,
        connectors_used_count: 0,
        distinct_connectors_used_count: 0,
      },
      powerpoint: {
        distinct_session_count: 0,
        message_count: 0,
        skills_used_count: 0,
        distinct_skills_used_count: 0,
        connectors_used_count: 0,
        distinct_connectors_used_count: 0,
      },
    },
    cowork_metrics: {
      distinct_session_count: 0,
      message_count: 0,
      action_count: 0,
      dispatch_turn_count: 0,
      skills_used_count: 0,
      distinct_skills_used_count: 0,
      connectors_used_count: 0,
      distinct_connectors_used_count: 0,
    },
  },
  {
    user: { id: 'user_carol', email_address: 'carol@example.com' },
    chat_metrics: {
      distinct_conversation_count: 1,
      message_count: 6,
      distinct_projects_created_count: 0,
      distinct_projects_used_count: 0,
      distinct_files_uploaded_count: 0,
      distinct_artifacts_created_count: 0,
      thinking_message_count: 0,
      distinct_skills_used_count: 0,
      connectors_used_count: 0,
    },
    claude_code_metrics: {
      core_metrics: {
        commit_count: 0,
        pull_request_count: 0,
        lines_of_code: { added_count: 0, removed_count: 0 },
        distinct_session_count: 0,
      },
      tool_actions: {
        edit_tool: { accepted_count: 0, rejected_count: 0 },
        multi_edit_tool: { accepted_count: 0, rejected_count: 0 },
        write_tool: { accepted_count: 0, rejected_count: 0 },
        notebook_edit_tool: { accepted_count: 0, rejected_count: 0 },
      },
    },
    web_search_count: 0,
    office_metrics: {
      excel: {
        distinct_session_count: 0,
        message_count: 0,
        skills_used_count: 0,
        distinct_skills_used_count: 0,
        connectors_used_count: 0,
        distinct_connectors_used_count: 0,
      },
      powerpoint: {
        distinct_session_count: 0,
        message_count: 0,
        skills_used_count: 0,
        distinct_skills_used_count: 0,
        connectors_used_count: 0,
        distinct_connectors_used_count: 0,
      },
    },
    cowork_metrics: {
      distinct_session_count: 0,
      message_count: 0,
      action_count: 0,
      dispatch_turn_count: 0,
      skills_used_count: 0,
      distinct_skills_used_count: 0,
      connectors_used_count: 0,
      distinct_connectors_used_count: 0,
    },
  },
];
