#!/usr/bin/env bash
# Insight platform — initialize after cluster is up.
#
# This script:
#   1. Verifies the cluster is reachable
#   2. Guides through secret creation if missing
#   3. Applies secrets
#   4. Deploys ClickHouse (if skipped during up.sh)
#   5. Runs ingestion init (databases, connectors, connections, workflows)
#
# Prerequisites: ./dev-up.sh must have been run first.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

KUBECONFIG_PATH="${KUBECONFIG:-${HOME}/.kube/insight.kubeconfig}"
export KUBECONFIG="${KUBECONFIG_PATH}"

echo "=== Insight Platform — Initialize ==="

# --- Verify cluster ---
if ! kubectl cluster-info &>/dev/null; then
  echo "ERROR: Cannot reach cluster. Run ./dev-up.sh first." >&2
  exit 1
fi

# --- Check and guide secrets ---
SECRETS_DIR="$ROOT_DIR/src/ingestion/secrets"
MISSING_SECRETS=()

check_secret_file() {
  local file="$1"
  local example="$2"
  local label="$3"
  if [[ ! -f "$file" ]]; then
    MISSING_SECRETS+=("$label: cp $example $file")
  fi
}

# ClickHouse credentials are auto-generated by up.sh — no manual secret needed

shopt -s nullglob
for example in "$SECRETS_DIR"/connectors/*.yaml.example; do
  base="$(basename "$example" .yaml.example)"
  target="$SECRETS_DIR/connectors/${base}.yaml"
  check_secret_file "$target" "$example" "Connector: $base"
done
shopt -u nullglob

if [[ ${#MISSING_SECRETS[@]} -gt 0 ]]; then
  echo ""
  echo "  Missing secret files (copy examples and fill in credentials):"
  echo ""
  for m in "${MISSING_SECRETS[@]}"; do
    echo "    $m"
  done
  echo ""
  echo "  After creating the files, re-run: ./init.sh"
  exit 1
fi

# --- Apply secrets ---
echo "=== Applying secrets ==="
"$SECRETS_DIR/apply.sh"

# --- Run ingestion init ---
echo "=== Running ingestion init ==="
cd "$ROOT_DIR/src/ingestion"
./run-init.sh

echo ""
echo "════════════════════════════════════════════════"
echo "  Initialization complete!"
echo ""
echo "  Services:"
echo "    Frontend:   http://localhost:8000"
echo "    API:        http://localhost:8000/api/v1"
echo "    Airbyte:    http://localhost:8001"
echo "    Argo UI:    http://localhost:30500"
echo "    ClickHouse: http://localhost:30123"
NAMESPACE="${INSIGHT_NAMESPACE:-insight}"
if kubectl get secret airbyte-auth-secrets -n "$NAMESPACE" &>/dev/null; then
  echo ""
  echo "  Airbyte UI login:"
  echo "    Email:    admin@example.com"
  echo "    Password: kubectl get secret airbyte-auth-secrets -n $NAMESPACE -o jsonpath='{.data.instance-admin-password}' | base64 -d"
fi
echo ""
echo "  Run a sync:"
echo "    cd src/ingestion && ./run-sync.sh <connector> <tenant>"
echo "════════════════════════════════════════════════"
