#!/usr/bin/env bash
# Apply connector K8s Secrets from local YAML to the cluster.
#
# Usage: ./apply.sh
#
# 1. Copy connectors/*.yaml.example → connectors/*.yaml
# 2. Fill in real credentials
# 3. Run this script
#
# Single-namespace umbrella (PR #224): all Insight components — including
# connector secrets — live in the release namespace, default `insight`.
# Override via INSIGHT_NAMESPACE for non-default installs. Infra credentials
# (ClickHouse/MariaDB/Redis) are auto-generated by the umbrella chart in
# `insight-db-creds` and are NOT applied from here.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSIGHT_NS="${INSIGHT_NAMESPACE:-insight}"

apply_dir() {
  local dir="$1"
  local label="$2"

  shopt -s nullglob
  local files=("$dir"/*.yaml)
  shopt -u nullglob

  if [[ ${#files[@]} -eq 0 ]]; then
    echo "No .yaml files in $dir"
    echo "  Copy .yaml.example files and fill in credentials:"
    for ex in "$dir"/*.yaml.example; do
      local base
      base="$(basename "$ex" .yaml.example).yaml"
      echo "    cp $ex $dir/$base"
    done
    return
  fi

  for f in "${files[@]}"; do
    echo "[$label] $(basename "$f") → $INSIGHT_NS"
    kubectl apply -f "$f" -n "$INSIGHT_NS"
  done
}

echo "=== Connector Secrets ==="
apply_dir "$DIR/connectors" "connector"

echo "Done."
